/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.ticket.management.system;


import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author goel1
 */
public class userdetails extends javax.swing.JFrame {
static String v,p,tripdat;
static int h;
//V IS USERNAME
//P IS BUSID
//TRIPDAT ID TRIP DATE
    /**
     * Creates new form NewJFrame
     */
    public userdetails() {
        initComponents();
        Login q=new Login();
        this.v=q.usrnm;
        busdetails w=new busdetails();
        this.p=w.busid;
        loginpage l=new loginpage();
        this.tripdat=l.tripdate;
        
    }
    public userdetails(int j)
    {
        this.h=j;//sends no. of users to j1 button for row count
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 550));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 340, 150, 40);

        t2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Sex", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(t2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(35, 109, 440, 200);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("No. of passangers");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(9, 24, 220, 40);
        getContentPane().add(t1);
        t1.setBounds(280, 40, 90, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 30, 70, 37);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(380, 460, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOOKNOW.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 0, 510, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            

//int m=Integer.parseInt(t1.getText());
Class.forName("oracle.jdbc.driver.OracleDriver");
Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","user","system");
int ticketid=0;

Statement st=con.createStatement();
ResultSet rs1=st.executeQuery("Select ticketid from ticketid");
while(rs1.next()){
    ticketid=rs1.getInt("Ticketid");
}
ticketid=++ticketid;
PreparedStatement pst2=con.prepareStatement("Update ticketid set TICKETID=?");
pst2.setInt(1, ticketid);
pst2.executeUpdate();
PreparedStatement pst=con.prepareStatement("Insert into UserDetails(USERNAME,NAME,AGE,GENDER,PHONE,BUSID,TRIPDATE,TICKETID) values (?,?,?,?,?,?,?,?)");
for(int k = 0; k<h; k++)
{
    String a = (String)t2.getValueAt(k, 0);
    String b = (String)t2.getValueAt(k, 1);
    String c = (String)t2.getValueAt(k, 2);
    String d = (String)t2.getValueAt(k, 3);
    pst.setString(1, v);
    pst.setString(2, a);
    pst.setString(3, b);
    pst.setString(4, c);
    pst.setString(5, d);
    pst.setString(6, p);
    pst.setString(7, tripdat);
    pst.setInt(8, ticketid);
    pst.addBatch();
    
}
int seatleft=0,seat=0;

//Statement st=con.createStatement();
ResultSet rs=st.executeQuery("Select SEAT from busdetails where BUSID='"+p+"'");
while(rs.next()){
    seat=rs.getInt("SEAT");
}
PreparedStatement pst1=con.prepareStatement("Update busdetails set SEAT=? where BUSID=?");
seatleft=seat-h;
pst1.setInt(1,seatleft);
pst1.setString(2, p);
pst.executeBatch();
pst1.executeUpdate();
JOptionPane.showMessageDialog(this,"Ticket Booked and TicketID is "+ticketid);

price o=new price();
o.setVisible(true);
this.dispose();

con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(this,e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int m=Integer.parseInt(t1.getText());
        userdetails f=new userdetails(m);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Login f=new Login();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField t1;
    private javax.swing.JTable t2;
    // End of variables declaration//GEN-END:variables
}
